version: '3'
services:
  frontend:
    container_name: "frontend"
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - .env
    networks:
      - app_net
    depends_on:
      - backend
  backend:
    container_name: "backend"
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    networks:
      - app_net
networks:
  app_net: